// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace KeyVaultClient.Models
{
    public partial class Secret
    {
        private string _contentType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ContentType
        {
            get { return this._contentType; }
            set { this._contentType = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _value;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Value
        {
            get { return this._value; }
            set { this._value = value; }
        }
        
        private int? _version;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Version
        {
            get { return this._version; }
            set { this._version = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Secret class.
        /// </summary>
        public Secret()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Secret
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ContentType != null)
            {
                outputObject["ContentType"] = this.ContentType;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.Value != null)
            {
                outputObject["Value"] = this.Value;
            }
            if (this.Version != null)
            {
                outputObject["Version"] = this.Version.Value;
            }
            return outputObject;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken contentTypeValue = inputObject["ContentType"];
                if (contentTypeValue != null && contentTypeValue.Type != JTokenType.Null)
                {
                    this.ContentType = ((string)contentTypeValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken valueValue = inputObject["Value"];
                if (valueValue != null && valueValue.Type != JTokenType.Null)
                {
                    this.Value = ((string)valueValue);
                }
                JToken versionValue = inputObject["Version"];
                if (versionValue != null && versionValue.Type != JTokenType.Null)
                {
                    this.Version = ((int)versionValue);
                }
            }
        }
    }
}
